theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  breadcrumb:
    position: after-hero
  logo:
    header: '/assets/images/logo-dark.svg'
    footer: '/assets/images/logo-light.svg'
  home:
    head:
      title: site
  image_sizes:
    sections:
      home:
        hero:
          mobile:   400
          tablet:   800
          desktop:  1650